apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jardvanroest/argocd-tutorial-2.git
    targetRevision: HEAD
    path: example-app
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
